[LangOptions]
LanguageName=Tiếng Việt
LanguageID=$042A
LanguageCodePage=65001
DialogFontName=Segoe UI
DialogFontSize=9
WelcomeFontName=Segoe UI
WelcomeFontSize=12
TitleFontName=Segoe UI
TitleFontSize=29
CopyrightFontName=Segoe UI
CopyrightFontSize=8

[Messages]
SetupAppTitle=Cài đặt
SetupWindowTitle=Cài đặt - %1
UninstallAppTitle=Gỡ cài đặt
UninstallAppFullTitle=Gỡ cài đặt %1
InformationTitle=Thông tin
ConfirmTitle=Xác nhận
ErrorTitle=Lỗi
SetupLdrStartupMessage=Chương trình sẽ cài đặt %1. Bạn có muốn tiếp tục?
LdrCannotCreateTemp=Không thể tạo tệp tạm. Quá trình cài đặt bị hủy.
LdrCannotExecTemp=Không thể chạy tệp trong thư mục tạm. Quá trình cài đặt bị hủy.
WelcomeLabel1=Chào mừng đến với trình cài đặt [name]
WelcomeLabel2=Chương trình sẽ cài đặt [name/ver] vào máy tính.%n%nBạn nên đóng các ứng dụng khác trước khi tiếp tục.
ClickNext=Bấm Tiếp theo để tiếp tục hoặc Hủy để thoát.
SelectDirLabel3=Chương trình sẽ cài [name] vào thư mục sau.
SelectDirBrowseLabel=Bấm Tiếp theo để tiếp tục. Bấm Duyệt nếu muốn chọn thư mục khác.
SelectStartMenuFolderDesc=Chương trình nên đặt lối tắt ở đâu?
SelectStartMenuFolderLabel3=Chọn thư mục Menu Bắt đầu cho lối tắt của chương trình.
SelectTasksDesc=Bạn muốn thực hiện thêm tác vụ nào?
SelectTasksLabel2=Chọn các tác vụ bổ sung rồi bấm Tiếp theo.
ReadyLabel1=Chương trình đã sẵn sàng để cài [name].
ReadyLabel2a=Bấm Cài đặt để bắt đầu hoặc Quay lại để xem và thay đổi thiết lập.
InstallingLabel=Vui lòng chờ trong khi [name] được cài vào máy tính.
FinishedHeadingLabel=Hoàn tất cài đặt [name]
FinishedLabelNoIcons=Đã cài [name] vào máy tính.
FinishedLabel=Đã cài [name] vào máy tính. Bạn có thể mở ứng dụng bằng biểu tượng đã tạo.
ClickFinish=Bấm Hoàn tất để đóng trình cài đặt.
ButtonBack=< Quay lại
ButtonNext=Tiếp theo >
ButtonInstall=Cài đặt
ButtonOK=Đồng ý
ButtonCancel=Hủy
ButtonYes=Có
ButtonYesToAll=Có với tất cả
ButtonNo=Không
ButtonNoToAll=Không với tất cả
ButtonFinish=Hoàn tất
ButtonBrowse=Duyệt...
ButtonWizardBrowse=Duyệt...
ButtonNewFolder=Tạo thư mục mới
SelectLanguageTitle=Chọn ngôn ngữ cài đặt
SelectLanguageLabel=Chọn ngôn ngữ dùng trong quá trình cài đặt:
ExitSetupTitle=Thoát trình cài đặt
ExitSetupMessage=Quá trình cài đặt chưa hoàn tất. Nếu thoát bây giờ, ứng dụng sẽ không được cài.%n%nBạn có chắc muốn thoát?
AboutSetupMenuItem=Giới thiệu trình cài đặt...
AboutSetupTitle=Giới thiệu trình cài đặt
AboutSetupMessage=%1 phiên bản %2%n%3%n%nTrang chủ:%n%4
UninstallNotFound=Không tìm thấy tệp "%1". Không thể gỡ cài đặt.
UninstallOpenAppsLabel2=Các ứng dụng sau đang dùng tệp cần cập nhật. Hãy để trình cài đặt tự đóng chúng.
UninstallStatusLabel=Vui lòng chờ trong khi %1 được gỡ khỏi máy tính.
UninstalledAll=%1 đã được gỡ khỏi máy tính.
UninstalledMost=Đã gỡ %1.%n%nMột số thành phần không thể xóa và có thể xóa thủ công.
